# @package _global_

defaults:
  - _self_
  - data: coco
  - model: segmentation
  - callbacks: default_eval
  - logger: tensorboard
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
